# Generated by Django 4.2.20 on 2025-04-18 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon", "0003_alter_pokemon_poke_dex_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokeapicache",
            name="stats",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
