# Generated by Django 5.1.7 on 2025-04-12 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon", "0001_initial"),
        ("trade", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="traderequest",
            name="receiver",
        ),
        migrations.RemoveField(
            model_name="traderequest",
            name="sender",
        ),
        migrations.RenameField(
            model_name="trade",
            old_name="timestamp",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="trade",
            name="initiator",
        ),
        migrations.AddField(
            model_name="trade",
            name="pokemon_offered",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="offered_in_trades",
                to="pokemon.pokemon",
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="pokemon_requested",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requested_in_trades",
                to="pokemon.pokemon",
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="requester",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trade_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("completed", "Completed"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="trade_type",
            field=models.CharField(
                choices=[("purchase", "Purchase"), ("trade", "Trade")],
                default=1,
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="trade",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="trade",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_trades",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="TradeDetail",
        ),
        migrations.DeleteModel(
            name="TradeRequest",
        ),
    ]
