# Generated by Django 4.2.20 on 2025-04-18 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon", "0004_pokeapicache_stats"),
        ("trade", "0003_purchase_remove_trade_trade_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.PositiveIntegerField()),
                ("completed", models.BooleanField(default=False)),
                (
                    "pokemon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pokemon.pokemon",
                    ),
                ),
            ],
        ),
    ]
