# Generated by Django 4.2.20 on 2025-04-19 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("trade", "0004_listing"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="purchase",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="trade",
        ),
        migrations.AddField(
            model_name="transaction",
            name="content_type",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="object_id",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
