# Generated by Django 4.2.20 on 2025-04-19 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pokemon", "0004_pokeapicache_stats"),
        ("trade", "0005_remove_transaction_purchase_remove_transaction_trade_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trade",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="trade",
            name="pokemon_offered",
        ),
        migrations.RemoveField(
            model_name="trade",
            name="pokemon_requested",
        ),
        migrations.RemoveField(
            model_name="trade",
            name="recipient",
        ),
        migrations.RemoveField(
            model_name="trade",
            name="requester",
        ),
        migrations.RemoveField(
            model_name="trade",
            name="status",
        ),
        migrations.RemoveField(
            model_name="trade",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="trade",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="trade",
            name="offerer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offer_owner",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trade",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="original_owner",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trade",
            name="pokemon",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offer",
                to="pokemon.pokemon",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="trade",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
