# Generated by Django 4.2.20 on 2025-04-19 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trade", "0006_remove_trade_created_at_remove_trade_pokemon_offered_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Purchase",
        ),
    ]
