# Generated by Django 4.2.20 on 2025-04-19 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon", "0004_pokeapicache_stats"),
        ("trade", "0007_delete_purchase"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trade",
            old_name="pokemon",
            new_name="offer",
        ),
        migrations.AddField(
            model_name="trade",
            name="original",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="original",
                to="pokemon.pokemon",
            ),
            preserve_default=False,
        ),
    ]
