# Generated by Django 4.2.20 on 2025-04-14 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pokemon', '0003_alter_pokemon_poke_dex_id'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='balance', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('balance', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ListingContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.PositiveIntegerField(blank=True, null=True)),
                ('pokemon', models.ManyToManyField(blank=True, to='pokemon.pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('ask', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asked_in', to='market.listingcontent')),
                ('offer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offered_in', to='market.listingcontent')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('poke_dex_id', models.IntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('FILLED', 'Filled')], default='OPEN', max_length=10)),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Asks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('poke_dex_id', models.IntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('FILLED', 'Filled')], default='OPEN', max_length=10)),
                ('asker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
