# Generated by Django 4.2.20 on 2025-04-18 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="balance",
            name="balance",
            field=models.PositiveIntegerField(default=5000),
        ),
    ]
