# Generated by Django 4.2.20 on 2025-04-18 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0002_alter_balance_balance"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Listing",
        ),
    ]
